require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# flipper_head_source = { :git => 'https://github.com/facebook/flipper.git', :branch => 'main' }

# flipper_versions = {
#   'Flipper'                  => '0.206.1',
#   'FlipperKit'               => '0.206.1',
#   'Flipper-Folly'            => '0.206.1',
#   'Flipper-RSocket'          => '0.206.1',
#   'Flipper-DoubleConversion' => '0.206.1',
#   'Flipper-Glog'             => '0.206.1',
#   'Flipper-PeerTalk'         => '0.206.1'
# }

# flipper_config =
#   ENV['NO_FLIPPER'] == '1' ?
#     FlipperConfiguration.disabled :
#     FlipperConfiguration.enabled(flipper_versions)

ENV['NO_FLIPPER'] = '1'
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

target 'UseHealthKitExample' do
  config = use_native_modules!
  flags  = get_default_flags()

  use_react_native!(
    :path              => config[:reactNativePath],
    :hermes_enabled    => flags[:hermes_enabled],
    :fabric_enabled    => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path          => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'UseHealthKitExampleTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer, :mac_catalyst_enabled => false)
  end
end
